name: presshop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.2+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  lottie: ^3.0.0
  otp_pin_field: ^1.1.2+2
  camera: ^0.11.3
  native_exif: ^0.6.0
  # gallery_saver: ^2.3.2
  location: ^7.0.1
  image_picker: ^1.1.2
  photo_manager: ^3.0.0-dev.5
  photo_manager_image_provider:
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.10
  audioplayers: ^6.1.1
  path_provider: ^2.1.2
  audio_waveforms: ^1.0.4
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
  google_places_flutter: ^2.0.5
  country_picker: ^2.0.20
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0
  file_picker: ^8.3.2
  another_flushbar: ^1.12.29
  geocoding: ^4.0.0
  google_sign_in: ^6.1.0
  firebase_core:
  firebase_auth: ^5.4.2
  cunning_document_scanner: ^1.1.2
  video_thumbnail: any
  # flutter_local_notifications: ^19.4.2
  cloud_firestore: any
  firebase_storage: any
  record: ^6.0.0
  emoji_picker_flutter: ^4.3.0
  cached_network_image: ^3.3.1
  internet_connection_checker: ^1.0.0+1
  flick_video_player: ^0.9.0
  firebase_messaging: ^15.2.2
  # device_info_plus: ^12.1.0
  firebase_analytics: ^11.4.4
  mime: ^2.0.0
  dots_indicator: ^3.0.0
  socket_io_client: ^3.0.2
  dio: ^5.8.0+1
#  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  webview_flutter: ^4.2.2
  app_links: ^6.3.3
  share_plus: ^10.1.4
  flutter_staggered_grid_view: ^0.7.0
  # syncfusion_flutter_pdfviewer: any
  flutter_slidable: ^3.0.0
  photo_view: ^0.15.0
  visibility_detector: ^0.4.0+2
  currency_text_input_formatter: any
  flutter_image_compress: ^2.0.4
  path: ^1.8.3
  google_maps_flutter: ^2.5.3
  fast_contacts: ^4.0.0
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.1
  # flutter_foreground_service: ^0.4.1
  clipboard: ^0.1.3
  fluttertoast: ^8.2.12
  firebase_crashlytics: ^4.3.4
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^31.2.4
  appsflyer_sdk: ^6.17.7
  facebook_app_events: ^0.20.1
  app_version_update: ^6.1.3
  # gallery_saver: ^2.3.2
  image_cropper: ^11.0.0
  http: ^1.2.2
  google_generative_ai: ^0.4.7
  geolocator: ^14.0.1
  flutter_local_notifications: ^19.5.0
  image_gallery_saver_plus: ^4.0.1
  dialog_flowtter: ^0.2.0-nullsafety.0
  upgrader: ^12.3.0
  force_update_helper: ^0.2.1
  flutter_lucide: ^1.7.0
  flutter_polyline_points: ^3.0.1
  image: ^4.5.4
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_riverpod: ^3.0.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  dartz: ^0.10.1
  flutter_dotenv: ^6.0.0
  # flutter_foreground_service: ^0.4.1
  # image_cropper: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/commonImages/
    - assets/dummyImages/
    - assets/icons/
    - assets/lottieFiles/
    - assets/audio/
    - assets/markers/
    - assets/rabbits/
    - assets/chatIcons/
    - assets/dialog_flow_auth.json

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf
